const apis = [
  {
    slug: 'payment-processing',
    name: 'Payment Processing',
    category: 'Payments',
    icon: '💳',
    featured: true,
    shortDescription: 'Accept payments, manage subscriptions, handle refunds',
    fullDescription:
      'Integrate comprehensive payment processing capabilities into your AI agents. Accept credit cards, manage recurring billing, handle refunds, and track transactions with full webhook support for real-time updates.',
    useCases: [
      'Process one-time payments',
      'Manage subscription billing',
      'Handle refunds and chargebacks',
      'Multi-currency transactions',
      'Invoice generation and tracking',
    ],
    documentation: 'https://docs.stripe.com/payments',
    baseUrl: 'https://jsonplaceholder.typicode.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '1000 requests/minute',
    pricing: 'Pay-as-you-go: 2.9% + $0.30 per transaction',
    webhook: true,
    endpoints: [
      {
        method: 'POST',
        path: '/posts',
        description: 'Create a new payment charge',
        parameters: [
          { name: 'title', type: 'string', required: true, description: 'Amount to charge' },
          { name: 'body', type: 'string', required: true, description: 'Payment description' },
        ],
        responseExample: { id: 101, title: 'Amount', body: 'USD 100', userId: 1 },
      },
      {
        method: 'GET',
        path: '/posts/{id}',
        description: 'Retrieve payment details',
        parameters: [{ name: 'id', type: 'number', required: true, description: 'Payment ID' }],
        responseExample: { userId: 1, id: 1, title: 'Payment Details', body: 'Charge succeeded' },
      },
      {
        method: 'POST',
        path: '/posts/{id}/comments',
        description: 'Process refund for a payment',
        parameters: [
          { name: 'id', type: 'number', required: true, description: 'Payment ID' },
          { name: 'name', type: 'string', required: true, description: 'Refund reason' },
        ],
        responseExample: { postId: 1, id: 1, name: 'Refund processed' },
      },
    ],
  },
  {
    slug: 'email-sms',
    name: 'Email & SMS',
    category: 'Communications',
    icon: '📧',
    featured: true,
    shortDescription: 'Send transactional emails, SMS notifications, marketing campaigns',
    fullDescription:
      'Enable your AI agents to communicate directly with users via email and SMS. Send transactional alerts, notifications, and marketing messages with templates, scheduling, and delivery tracking.',
    useCases: [
      'Send verification codes',
      'Transaction notifications',
      'Alert users to important events',
      'Schedule bulk campaigns',
      'Track delivery and engagement',
    ],
    documentation: 'https://docs.sendgrid.com',
    baseUrl: 'https://jsonplaceholder.typicode.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '10000 emails/hour, 1000 SMS/minute',
    pricing: 'Email: $0.001 per message, SMS: $0.0075 per message',
    webhook: true,
    endpoints: [
      {
        method: 'POST',
        path: '/posts',
        description: 'Send an email',
        parameters: [
          { name: 'title', type: 'string', required: true, description: 'Email subject' },
          { name: 'body', type: 'string', required: true, description: 'Email body' },
        ],
        responseExample: { id: 101, title: 'Welcome', body: 'Thank you for signing up' },
      },
      {
        method: 'GET',
        path: '/posts',
        description: 'List sent emails',
        parameters: [
          { name: '_limit', type: 'number', required: false, description: 'Limit results' },
        ],
        responseExample: [{ id: 1, title: 'Email 1', body: 'Content' }],
      },
    ],
  },
  {
    slug: 'data-enrichment',
    name: 'Data Enrichment',
    category: 'Data',
    icon: '📊',
    featured: true,
    shortDescription: 'Enrich leads with company data, verify emails, phone lookup',
    fullDescription:
      'Enhance your AI agent capabilities with real-time data enrichment. Verify emails, perform phone lookups, get company insights, and enrich contact records with up-to-date information from multiple sources.',
    useCases: [
      'Email verification and validation',
      'Phone number lookup and verification',
      'Company information enrichment',
      'Lead scoring and qualification',
      'Account identification',
    ],
    documentation: 'https://docs.peopledatalabs.com',
    baseUrl: 'https://jsonplaceholder.typicode.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '500 requests/minute',
    pricing: 'Email verification: $0.01/lookup, Phone: $0.02/lookup, Company: $0.05/lookup',
    webhook: false,
    endpoints: [
      {
        method: 'GET',
        path: '/users',
        description: 'Search for person information',
        parameters: [
          { name: '_limit', type: 'number', required: false, description: 'Limit results' },
        ],
        responseExample: { id: 1, name: 'John Doe', username: 'johnd', email: 'john@example.com' },
      },
      {
        method: 'GET',
        path: '/users/{id}',
        description: 'Get detailed person information',
        parameters: [
          { name: 'id', type: 'number', required: true, description: 'User ID' },
        ],
        responseExample: { id: 1, name: 'Leanne Graham', username: 'Bret', email: 'Sincere@april.biz' },
      },
    ],
  },
  {
    slug: 'web-scraping',
    name: 'Web Scraping',
    category: 'Data Collection',
    icon: '🕷️',
    featured: true,
    shortDescription: 'Extract data from any website, structured web crawling',
    fullDescription:
      'Empower your AI agents to gather information from the web. Scrape websites, extract structured data, handle JavaScript rendering, and parse complex HTML with intelligent data extraction tailored to your needs.',
    useCases: [
      'Extract product information',
      'Gather pricing data',
      'Monitor competitor websites',
      'Collect news and articles',
      'Extract contact information from businesses',
    ],
    documentation: 'https://docs.brightdata.com/scraping',
    baseUrl: 'https://jsonplaceholder.typicode.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '100 requests/minute',
    pricing: '$0.01 per request, $5/1000 requests',
    webhook: false,
    endpoints: [
      {
        method: 'GET',
        path: '/posts',
        description: 'Scrape and list web content',
        parameters: [
          { name: '_limit', type: 'number', required: false, description: 'Number of results' },
          { name: '_start', type: 'number', required: false, description: 'Start index' },
        ],
        responseExample: { userId: 1, id: 1, title: 'Web Content', body: 'Scraped data' },
      },
      {
        method: 'GET',
        path: '/posts/{id}',
        description: 'Get specific scraped content',
        parameters: [
          { name: 'id', type: 'number', required: true, description: 'Content ID' },
        ],
        responseExample: { userId: 1, id: 1, title: 'Page Title', body: 'Page content' },
      },
    ],
  },
  {
    slug: 'identity-verification',
    name: 'Identity Verification',
    category: 'Compliance',
    icon: '✓',
    featured: true,
    shortDescription: 'Phone verification, KYC checks, document validation',
    fullDescription:
      'Implement robust identity verification and Know Your Customer (KYC) processes in your AI agent workflows. Verify phone numbers, validate documents, and ensure compliance with regulatory requirements.',
    useCases: [
      'Phone number verification',
      'KYC/AML compliance checks',
      'Document verification',
      'Biometric verification',
      'Address validation',
    ],
    documentation: 'https://docs.jumio.com',
    baseUrl: 'https://jsonplaceholder.typicode.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '1000 requests/minute',
    pricing: 'Phone verification: $0.05, KYC: $0.50, Document: $1.00',
    webhook: true,
    endpoints: [
      {
        method: 'POST',
        path: '/posts',
        description: 'Start phone verification',
        parameters: [
          { name: 'title', type: 'string', required: true, description: 'Phone number' },
          { name: 'body', type: 'string', required: true, description: 'Verification method (sms/call)' },
        ],
        responseExample: { id: 101, title: '+1234567890', body: 'sms' },
      },
      {
        method: 'GET',
        path: '/posts/{id}',
        description: 'Check verification status',
        parameters: [
          { name: 'id', type: 'number', required: true, description: 'Session ID' },
        ],
        responseExample: { id: 1, title: 'Verification', body: 'pending' },
      },
    ],
  },
  {
    slug: 'analytics-tracking',
    name: 'Analytics & Tracking',
    category: 'Analytics',
    icon: '📈',
    featured: true,
    shortDescription: 'Track events, user behavior, generate reports',
    fullDescription:
      'Enable your AI agents to track events, monitor user behavior, and generate comprehensive analytics reports. Understand agent performance, user interactions, and system metrics in real-time dashboards.',
    useCases: [
      'Track agent interactions',
      'Monitor feature usage',
      'Generate performance reports',
      'Track conversion funnels',
      'Analyze user behavior patterns',
    ],
    documentation: 'https://docs.mixpanel.com',
    baseUrl: 'https://jsonplaceholder.typicode.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '100000 requests/minute',
    pricing: '$99/month for up to 10M events, then $0.01 per 1K events',
    webhook: false,
    endpoints: [
      {
        method: 'POST',
        path: '/posts',
        description: 'Track an event',
        parameters: [
          { name: 'title', type: 'string', required: true, description: 'Event name' },
          { name: 'body', type: 'string', required: true, description: 'Event details' },
        ],
        responseExample: { id: 101, title: 'page_view', body: 'tracked' },
      },
      {
        method: 'GET',
        path: '/posts',
        description: 'Get analytics summary',
        parameters: [
          { name: '_limit', type: 'number', required: false, description: 'Limit results' },
        ],
        responseExample: [{ id: 1, title: 'Event 1', body: 'Details' }],
      },
    ],
  },
  {
    slug: 'file-processing',
    name: 'File Processing',
    category: 'Document Processing',
    icon: '📄',
    featured: true,
    shortDescription: 'PDF extraction, image analysis, document parsing',
    fullDescription:
      'Integrate intelligent file processing into your AI agents. Extract text and data from PDFs, analyze images, parse documents, and convert files to various formats with automatic content understanding.',
    useCases: [
      'Extract text from PDFs',
      'Analyze and tag images',
      'Parse invoices and receipts',
      'OCR from scanned documents',
      'Document classification',
    ],
    documentation: 'https://docs.cloudmersive.com',
    baseUrl: 'https://jsonplaceholder.typicode.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '500 requests/minute',
    pricing: 'PDF extraction: $0.05/page, Image analysis: $0.02/image',
    webhook: false,
    endpoints: [
      {
        method: 'POST',
        path: '/posts',
        description: 'Extract text from file',
        parameters: [
          { name: 'title', type: 'string', required: true, description: 'File name' },
          { name: 'body', type: 'string', required: true, description: 'File URL' },
        ],
        responseExample: { id: 101, title: 'document.pdf', body: 'Extracted text' },
      },
      {
        method: 'GET',
        path: '/posts',
        description: 'List processed files',
        parameters: [
          { name: '_limit', type: 'number', required: false, description: 'Limit results' },
        ],
        responseExample: [{ id: 1, title: 'file.pdf', body: 'Processed' }],
      },
    ],
  },
  {
    slug: 'search-discovery',
    name: 'Search & Discovery',
    category: 'Search',
    icon: '🔍',
    featured: true,
    shortDescription: 'Web search, content extraction, semantic search',
    fullDescription:
      'Empower your AI agents with powerful search capabilities. Perform web searches, semantic searches, and content discovery with intelligent ranking and relevance scoring to find exactly what you need.',
    useCases: [
      'Web search integration',
      'News and article discovery',
      'Semantic similarity search',
      'Content recommendations',
      'Knowledge graph queries',
    ],
    documentation: 'https://docs.algolia.com',
    baseUrl: 'https://jsonplaceholder.typicode.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '1000 requests/minute',
    pricing: 'Pay-as-you-go: $0.01 per search',
    webhook: false,
    endpoints: [
      {
        method: 'GET',
        path: '/posts',
        description: 'Perform web search',
        parameters: [
          { name: '_limit', type: 'number', required: false, description: 'Number of results' },
          { name: '_sort', type: 'string', required: false, description: 'Sort field' },
        ],
        responseExample: { id: 1, title: 'Search Result', body: 'Content' },
      },
      {
        method: 'POST',
        path: '/posts',
        description: 'Semantic search',
        parameters: [
          { name: 'title', type: 'string', required: true, description: 'Search query' },
          { name: 'body', type: 'string', required: true, description: 'Content to search' },
        ],
        responseExample: { id: 101, title: 'Query', body: 'Results' },
      },
    ],
  },
];

module.exports = { apis };
