const apis = [
  {
    slug: 'payment-processing',
    name: 'Payment Processing',
    category: 'Payments',
    icon: '💳',
    featured: true,
    shortDescription: 'Accept payments, manage subscriptions, handle refunds',
    fullDescription:
      'Integrate comprehensive payment processing capabilities into your AI agents. Accept credit cards, manage recurring billing, handle refunds, and track transactions with full webhook support for real-time updates.',
    useCases: [
      'Process one-time payments',
      'Manage subscription billing',
      'Handle refunds and chargebacks',
      'Multi-currency transactions',
      'Invoice generation and tracking',
    ],
    documentation: 'https://docs.stripe.com/payments',
    authentication: 'API Key (Bearer token)',
    rateLimit: '1000 requests/minute',
    pricing: 'Pay-as-you-go: 2.9% + $0.30 per transaction',
    webhook: true,
    endpoints: [
      {
        method: 'POST',
        path: '/v1/payments/charge',
        description: 'Create a new payment charge',
        parameters: [
          { name: 'amount', type: 'number', required: true, description: 'Amount in cents' },
          { name: 'currency', type: 'string', required: true, description: 'ISO 4217 currency code' },
          { name: 'description', type: 'string', required: false, description: 'Payment description' },
        ],
        responseExample: { id: 'ch_1234', amount: 10000, status: 'succeeded' },
      },
      {
        method: 'GET',
        path: '/v1/payments/{id}',
        description: 'Retrieve payment details',
        parameters: [{ name: 'id', type: 'string', required: true, description: 'Payment ID' }],
        responseExample: { id: 'ch_1234', amount: 10000, status: 'succeeded', created: 1234567890 },
      },
      {
        method: 'POST',
        path: '/v1/refunds',
        description: 'Refund a payment',
        parameters: [
          { name: 'payment_id', type: 'string', required: true, description: 'Payment to refund' },
          { name: 'reason', type: 'string', required: false, description: 'Refund reason' },
        ],
        responseExample: { id: 'ref_1234', payment_id: 'ch_1234', status: 'succeeded' },
      },
    ],
  },
  {
    slug: 'email-sms',
    name: 'Email & SMS',
    category: 'Communications',
    icon: '📧',
    featured: true,
    shortDescription: 'Send transactional emails, SMS notifications, marketing campaigns',
    fullDescription:
      'Enable your AI agents to communicate directly with users via email and SMS. Send transactional alerts, notifications, and marketing messages with templates, scheduling, and delivery tracking.',
    useCases: [
      'Send verification codes',
      'Transaction notifications',
      'Alert users to important events',
      'Schedule bulk campaigns',
      'Track delivery and engagement',
    ],
    documentation: 'https://docs.sendgrid.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '10000 emails/hour, 1000 SMS/minute',
    pricing: 'Email: $0.001 per message, SMS: $0.0075 per message',
    webhook: true,
    endpoints: [
      {
        method: 'POST',
        path: '/v1/email/send',
        description: 'Send an email',
        parameters: [
          { name: 'to', type: 'string', required: true, description: 'Recipient email address' },
          { name: 'subject', type: 'string', required: true, description: 'Email subject' },
          { name: 'body', type: 'string', required: true, description: 'Email body (HTML supported)' },
        ],
        responseExample: { id: 'email_1234', status: 'sent', timestamp: 1234567890 },
      },
      {
        method: 'POST',
        path: '/v1/sms/send',
        description: 'Send an SMS',
        parameters: [
          { name: 'phone', type: 'string', required: true, description: 'Recipient phone number' },
          { name: 'message', type: 'string', required: true, description: 'SMS message (160 chars)' },
        ],
        responseExample: { id: 'sms_5678', status: 'queued', timestamp: 1234567890 },
      },
    ],
  },
  {
    slug: 'data-enrichment',
    name: 'Data Enrichment',
    category: 'Data',
    icon: '📊',
    featured: true,
    shortDescription: 'Enrich leads with company data, verify emails, phone lookup',
    fullDescription:
      'Enhance your AI agent capabilities with real-time data enrichment. Verify emails, perform phone lookups, get company insights, and enrich contact records with up-to-date information from multiple sources.',
    useCases: [
      'Email verification and validation',
      'Phone number lookup and verification',
      'Company information enrichment',
      'Lead scoring and qualification',
      'Account identification',
    ],
    documentation: 'https://docs.peopledatalabs.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '500 requests/minute',
    pricing: 'Email verification: $0.01/lookup, Phone: $0.02/lookup, Company: $0.05/lookup',
    webhook: false,
    endpoints: [
      {
        method: 'POST',
        path: '/v1/email/verify',
        description: 'Verify an email address',
        parameters: [{ name: 'email', type: 'string', required: true, description: 'Email to verify' }],
        responseExample: { email: 'test@example.com', valid: true, smtp_check: true },
      },
      {
        method: 'GET',
        path: '/v1/person/search',
        description: 'Search for person information',
        parameters: [
          { name: 'email', type: 'string', required: false, description: 'Email address' },
          { name: 'name', type: 'string', required: false, description: 'Full name' },
        ],
        responseExample: { id: 'p_123', name: 'John Doe', title: 'CEO', company: 'Acme Corp' },
      },
    ],
  },
  {
    slug: 'web-scraping',
    name: 'Web Scraping',
    category: 'Data Collection',
    icon: '🕷️',
    featured: true,
    shortDescription: 'Extract data from any website, structured web crawling',
    fullDescription:
      'Empower your AI agents to gather information from the web. Scrape websites, extract structured data, handle JavaScript rendering, and parse complex HTML with intelligent data extraction tailored to your needs.',
    useCases: [
      'Extract product information',
      'Gather pricing data',
      'Monitor competitor websites',
      'Collect news and articles',
      'Extract contact information from businesses',
    ],
    documentation: 'https://docs.brightdata.com/scraping',
    authentication: 'API Key (Bearer token)',
    rateLimit: '100 requests/minute',
    pricing: '$0.01 per request, $5/1000 requests',
    webhook: false,
    endpoints: [
      {
        method: 'POST',
        path: '/v1/scrape',
        description: 'Scrape a webpage',
        parameters: [
          { name: 'url', type: 'string', required: true, description: 'URL to scrape' },
          { name: 'selector', type: 'string', required: false, description: 'CSS selector for target elements' },
          { name: 'javascript', type: 'boolean', required: false, description: 'Render JavaScript' },
        ],
        responseExample: { url: 'https://example.com', content: '<html>...</html>', status: 200 },
      },
    ],
  },
  {
    slug: 'identity-verification',
    name: 'Identity Verification',
    category: 'Compliance',
    icon: '✓',
    featured: true,
    shortDescription: 'Phone verification, KYC checks, document validation',
    fullDescription:
      'Implement robust identity verification and Know Your Customer (KYC) processes in your AI agent workflows. Verify phone numbers, validate documents, and ensure compliance with regulatory requirements.',
    useCases: [
      'Phone number verification',
      'KYC/AML compliance checks',
      'Document verification',
      'Biometric verification',
      'Address validation',
    ],
    documentation: 'https://docs.jumio.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '1000 requests/minute',
    pricing: 'Phone verification: $0.05, KYC: $0.50, Document: $1.00',
    webhook: true,
    endpoints: [
      {
        method: 'POST',
        path: '/v1/verify/phone',
        description: 'Send phone verification code',
        parameters: [
          { name: 'phone', type: 'string', required: true, description: 'Phone number' },
          { name: 'method', type: 'string', required: false, description: 'sms or call' },
        ],
        responseExample: { session_id: 'vs_123', phone: '+1234567890', status: 'pending' },
      },
      {
        method: 'POST',
        path: '/v1/verify/kyc',
        description: 'Start KYC verification',
        parameters: [
          { name: 'first_name', type: 'string', required: true, description: 'First name' },
          { name: 'last_name', type: 'string', required: true, description: 'Last name' },
          { name: 'date_of_birth', type: 'string', required: true, description: 'DOB in YYYY-MM-DD' },
        ],
        responseExample: { session_id: 'kyc_123', status: 'pending_review' },
      },
    ],
  },
  {
    slug: 'analytics-tracking',
    name: 'Analytics & Tracking',
    category: 'Analytics',
    icon: '📈',
    featured: true,
    shortDescription: 'Track events, user behavior, generate reports',
    fullDescription:
      'Enable your AI agents to track events, monitor user behavior, and generate comprehensive analytics reports. Understand agent performance, user interactions, and system metrics in real-time dashboards.',
    useCases: [
      'Track agent interactions',
      'Monitor feature usage',
      'Generate performance reports',
      'Track conversion funnels',
      'Analyze user behavior patterns',
    ],
    documentation: 'https://docs.mixpanel.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '100000 requests/minute',
    pricing: '$99/month for up to 10M events, then $0.01 per 1K events',
    webhook: false,
    endpoints: [
      {
        method: 'POST',
        path: '/v1/events/track',
        description: 'Track an event',
        parameters: [
          { name: 'event_name', type: 'string', required: true, description: 'Event name' },
          { name: 'properties', type: 'object', required: true, description: 'Event properties' },
        ],
        responseExample: { event_id: 'evt_123', received: true },
      },
      {
        method: 'GET',
        path: '/v1/reports/summary',
        description: 'Get analytics summary',
        parameters: [
          { name: 'start_date', type: 'string', required: true, description: 'Start date (YYYY-MM-DD)' },
          { name: 'end_date', type: 'string', required: true, description: 'End date (YYYY-MM-DD)' },
        ],
        responseExample: { total_events: 10000, unique_users: 500, conversion_rate: 0.12 },
      },
    ],
  },
  {
    slug: 'file-processing',
    name: 'File Processing',
    category: 'Document Processing',
    icon: '📄',
    featured: true,
    shortDescription: 'PDF extraction, image analysis, document parsing',
    fullDescription:
      'Integrate intelligent file processing into your AI agents. Extract text and data from PDFs, analyze images, parse documents, and convert files to various formats with automatic content understanding.',
    useCases: [
      'Extract text from PDFs',
      'Analyze and tag images',
      'Parse invoices and receipts',
      'OCR from scanned documents',
      'Document classification',
    ],
    documentation: 'https://docs.cloudmersive.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '500 requests/minute',
    pricing: 'PDF extraction: $0.05/page, Image analysis: $0.02/image',
    webhook: false,
    endpoints: [
      {
        method: 'POST',
        path: '/v1/files/extract-text',
        description: 'Extract text from file',
        parameters: [
          { name: 'file_url', type: 'string', required: true, description: 'URL to file' },
          { name: 'file_type', type: 'string', required: false, description: 'pdf, image, docx' },
        ],
        responseExample: { text: 'Extracted text...', pages: 5, confidence: 0.95 },
      },
      {
        method: 'POST',
        path: '/v1/files/analyze-image',
        description: 'Analyze an image',
        parameters: [
          { name: 'image_url', type: 'string', required: true, description: 'URL to image' },
        ],
        responseExample: { objects: ['person', 'car'], labels: ['outdoor', 'daytime'], confidence: 0.89 },
      },
    ],
  },
  {
    slug: 'search-discovery',
    name: 'Search & Discovery',
    category: 'Search',
    icon: '🔍',
    featured: true,
    shortDescription: 'Web search, content extraction, semantic search',
    fullDescription:
      'Empower your AI agents with powerful search capabilities. Perform web searches, semantic searches, and content discovery with intelligent ranking and relevance scoring to find exactly what you need.',
    useCases: [
      'Web search integration',
      'News and article discovery',
      'Semantic similarity search',
      'Content recommendations',
      'Knowledge graph queries',
    ],
    documentation: 'https://docs.algolia.com',
    authentication: 'API Key (Bearer token)',
    rateLimit: '1000 requests/minute',
    pricing: 'Pay-as-you-go: $0.01 per search',
    webhook: false,
    endpoints: [
      {
        method: 'GET',
        path: '/v1/search/web',
        description: 'Perform web search',
        parameters: [
          { name: 'q', type: 'string', required: true, description: 'Search query' },
          { name: 'limit', type: 'number', required: false, description: 'Number of results (max 50)' },
        ],
        responseExample: {
          results: [{ title: 'Result 1', url: 'https://...', snippet: 'Preview...' }],
          total: 1000000,
        },
      },
      {
        method: 'POST',
        path: '/v1/search/semantic',
        description: 'Semantic search',
        parameters: [
          { name: 'query', type: 'string', required: true, description: 'Search query' },
          { name: 'documents', type: 'array', required: true, description: 'Documents to search' },
        ],
        responseExample: { results: [{ document: 'doc 1', score: 0.95 }] },
      },
    ],
  },
];

module.exports = { apis };
